titles = [
"0 Préface",
"1 Bénédiction",
"2 L'albatros",
"3 Élévation",
"4 Correspondances",
"5 J'aime le souvenir de ces époques nues",
"6 Les phares",
"7 La muse malade",
"8 La muse vénale",
"9 Le mauvais moine",
"10 L'ennemi",
"11 Le guignon",
"12 La vie antérieure",
"13 Bohémiens en voyage",
"14 L'homme et la mer",
"15 Don Juan aux enfers",
"16 À Théodore de Banville (1842)",
"17 Châtiment de l'orgueil",
"18 La beauté",
"19 L'idéal",
"20 La géante",
"21 Le masque (statue allégorique dans le goût de la Renaissance)",
"22 Hymne à la beauté",
"23 Parfum exotique",
"24 La chevelure",
"25 Je t'adore à l'égal de la voûte nocturne",
"26 Tu mettrais l'univers entier dans ta ruelle",
"27 Sed non satiata",
"28 Avec ses vêtements ondoyants et nacrés",
"29 Le serpent qui danse",
"30 Une charogne",
"31 De profundis clamavi",
"32 Le vampire",
"33 Une nuit que j'étais près d'une affreuse Juive",
"34 Remords posthume",
"35 Le chat",
"36 Duellum",
"37 Le balcon",
"38 Le possédé",
"39 Un fantôme",
"40 Je te donne ces vers afin que si mon nom",
"41 Semper eadem",
"42 Tout entière",
"43 Que diras-tu ce soir, pauvre âme solitaire",
"44 Le flambeau vivant",
"45 Réversibilité",
"46 Confession",
"47 L'aube spirituelle",
"48 Harmonie du soir",
"49 Le flacon",
"50 Le poison",
"51 Ciel brouillé",
"52 Le chat",
"53 Le beau navire",
"54 L'invitation au voyage",
"55 L'irréparable",
"56 Causerie",
"57 Chant d'automne",
"58 À une madone (ex-voto dans le goût espagnol)",
"59 Chanson d'après-midi",
"60 Sisina",
"61 Vers pour le portrait d'Honoré Daumier",
"62 Franciscae meae laudes",
"63 À une dame créole",
"64 Moesta et errabunda",
"65 Le revenant",
"66 Sonnet d'automne",
"67 Tristesse de la lune",
"68 Les chats",
"69 Les hiboux",
"70 La pipe",
"71 La musique",
"72 Sépulture d'un poète maudit",
"73 Une gravure fantastique",
"74 Le mort joyeux",
"75 Le tonneau de la haine",
"76 La cloche fêlée",
"77 Spleen (Pluviôse, irritée contre la vie entière)",
"78 Spleen (J'ai plus de souvenirs que si j'avais mille ans)",
"79 Spleen (Je suis comme un roi d'un pays pluvieux)",
"80 Spleen (Quand le ciel bas et lourd pèse comme un couvercle)",
"81 Obsession",
"82 Le goût du néant",
"83 Alchimie de la douleur",
"84 Horreur sympathique",
"85 Le calumet de paix (imité de Longfellow)",
"86 La prière d'un païen",
"87 Le couvercle",
"88 L'imprévu",
"89 L'examen de minuit",
"90 Madrigal triste",
"91 L'avertisseur",
"92 À une Malabaraise",
"93 La voix",
"94 Hymne",
"95 Le rebelle",
"96 Les yeux de Berthe",
"97 Le jet d'eau",
"98 La rançon",
"99 Bien loin d'ici",
"100 Le coucher du soleil romantique",
"101 Sur le Tasse en Prison d'Eugène Delacroix",
"102 Le gouffre",
"103 Les plaintes d'un Icare",
"104 Recueillement",
"105 L'héautontimorouménos",
"106 L'irrémédiable",
"107 L'horloge",
"108 Paysage",
"109 Le soleil",
"110 Lola de Valence (description pour le tableau d'Édouard Manet)",
"111 La lune offensée",
"112 À une mendiante rousse",
"113 Le cygne",
"114 Les sept vieillards",
"115 Les petites vieilles",
"116 Les aveugles",
"117 À une passante",
"118 Le squelette laboureur",
"119 Le crépuscule du soir",
"120 Le jeu",
"121 Danse macabre",
"122 L'amour du mensonge",
"123 Je n'ai pas oublié, voisine de la ville",
"124 La servante au grand coeur dont vous étiez jalouse",
"125 Brumes et pluies",
"126 Rêve parisien",
"127 Le crépuscule du matin",
"129 Le vin des chiffonniers",
"130 Le vin de l'assassin",
"131 Le vin du solitaire",
"132 Le vin des amants",
"133 Épigraphe pour un livre condamné",
"134 La destruction",
"135 Une martyre (dessin d'un maître inconnu)",
"136 Femmes damnées",
"137 Les deux bonnes soeurs",
"138 La fontaine de sang",
"139 Allégorie",
"140 La Béatrice",
"141 Un voyage à Cythère",
"142 L'amour et le crâne (vieux cul-de-lampe)",
"143 Le reniement de Saint Pierre",
"144 Abel et Caïn",
"145 Les litanies de Satan",
"146 La mort des amants",
"147 La mort des pauvres",
"148 La mort des artistes",
"149 La fin de la journée",
"150 Le rêve d'un curieux",
"151 Le voyage"]
